detect python files to install playwright

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,4 +1,13 @@
 #!/bin/sh
 
-echo "Playwright"
+# Fail immediately if any errors occur
+set -e
+
+echo "-----> Detecting Playwright"
+
+if [[ ! -f "requirements.txt" ]] && [[ ! -f "pyproject.toml" ]] && [[ ! -f "Pipfile" ]]; then
+  echo "       No requirements.txt, pyproject.toml, or Pipfile found"
+  exit 1
+fi
+
 exit 0
